In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
path = 'C:/Users/shisk/Desktop/Projects/Data/mobile_phone_data.csv'

In [4]:
df = pd.read_csv(path)
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range,id
0,842,0,2.2,0,1,0,7,0.6,188,2,...,756,2549,9,7,19,0,0,1,1.0,NaN
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,1988,2631,17,3,7,1,1,0,2.0,NaN
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1716,2603,11,2,9,1,1,0,2.0,NaN
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1786,2769,16,8,11,1,0,0,2.0,NaN
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1212,1411,8,2,15,1,1,0,1.0,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   battery_power  3000 non-null   int64
 1   blue           3000 non-null   int64
 2   clock_speed    3000 non-null   float64
 3   dual_sim       3000 non-null   int64
 4   fc             3000 non-null   int64
 5   four_g         3000 non-null   int64
 6   int_memory     3000 non-null   int64
 7   m_dep          3000 non-null   float64
 8   mobile_wt      3000 non-null   int64
 9   n_cores        3000 non-null   int64
 10  pc             3000 non-null   int64
 11  px_height      3000 non-null   int64
 12  px_width       3000 non-null   int64
 13  ram            3000 non-null   int64
 14  sc_h           3000 non-null   int64
 15  sc_w           3000 non-null   int64
 16  talk_time      3000 non-null   int64
 17  three_g        3000 non-null   int64
 18  touch_screen   3000 non-null   int64
 19  wifi           3000 non-null   int64
 20  price_range    2000 non-null   float64
 21  id             1000 non-null   float64
dtypes: float64(4), int64(18)
memory usage: 515.8 KB

In [6]:
df.isnull().sum()

battery_power       0
blue                0
clock_speed         0
dual_sim            0
fc                  0
four_g              0
int_memory          0
m_dep               0
mobile_wt           0
n_cores             0
pc                  0
px_height           0
px_width            0
ram                 0
sc_h                0
sc_w                0
talk_time           0
three_g             0
touch_screen        0
wifi                0
price_range      1000
id               2000
dtype: int64

In [8]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
battery_power,3000.0,1241.849000,437.063804,500.0,863.75,1232.0,1619.00,1999.0
blue,3000.0,0.502000,0.500079,0.0,0.00,1.0,1.00,1.0
clock_speed,3000.0,1.528467,0.820358,0.5,0.70,1.5,2.30,3.0
dual_sim,3000.0,0.512000,0.499939,0.0,0.00,1.0,1.00,1.0
fc,3000.0,4.404000,4.383742,0.0,1.00,3.0,7.00,19.0
four_g,3000.0,0.510000,0.499983,0.0,0.00,1.0,1.00,1.0
int_memory,3000.0,32.581667,18.152810,2.0,16.00,33.0,48.00,64.0
m_dep,3000.0,0.507000,0.285969,0.1,0.20,0.5,0.80,1.0
mobile_wt,3000.0,140.003000,35.213809,80.0,109.00,140.0,170.00,200.0
n_cores,3000.0,4.456333,2.289361,1.0,2.00,4.0,6.00,8.0
pc,3000.0,9.962333,6.073923,0.0,5.00,10.0,15.00,20.0
px_height,3000.0,639.112333,440.202998,0.0,277.75,564.0,932.50,1960.0
px_width,3000.0,1247.601667,434.666168,500.0,865.00,1248.0,1634.00,1998.0
ram,3000.0,2129.141333,1085.694231,256.0,1212.75,2147.5,3065.25,3998.0
sc_h,3000.0,12.202667,4.251151,5.0,9.00,12.0,16.00,19.0
sc_w,3000.0,5.616667,4.322494,0.0,2.00,5.0,9.00,18.0
talk_time,3000.0,11.035667,5.474400,2.0,6.00,11.0,16.00,20.0
three_g,3000.0,0.759667,0.427357,0.0,1.00,1.0,1.00,1.0
touch_screen,3000.0,0.502000,0.500079,0.0,0.00,1.0,1.00,1.0
wifi,3000.0,0.507000,0.500034,0.0,0.00,1.0,1.00,1.0
price_range,2000.0,1.500000,1.118314,0.0,0.75,1.5,2.25,3.0
id,1000.0,500.500000,288.819436,1.0,250.75,500.5,750.25,1000.0

In [10]:
df['id'].value_counts()

971.0    1
620.0    1
460.0    1
956.0    1
436.0    1
        ..
837.0    1
775.0    1
737.0    1
707.0    1
1.0      1
Name: id, Length: 1000, dtype: int64

In [11]:
# drop 'id' column
df.drop('id', axis = 1, inplace = True)

In [14]:
# drop data with no price labels
df.dropna(axis = 0, inplace = True)
df.isnull().sum()

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [17]:
df['price_range'].value_counts()

0.0    500
3.0    500
2.0    500
1.0    500
Name: price_range, dtype: int64

## Data Standardization

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [20]:
sc.fit(df.drop(labels = ['price_range'], axis = 1))

StandardScaler()

In [21]:
sc_features = sc.transform(df.drop('price_range', axis = 1))

In [25]:
columns = df.columns[:-1]

In [26]:
df_feat = pd.DataFrame(sc_features, columns = columns)
df_feat.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,pc,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi
0,-0.902597,-0.990050,0.830779,-1.019184,-0.762495,-1.043966,-1.380644,0.340740,1.349249,-1.101971,-1.305750,-1.408949,-1.146784,0.391703,-0.784983,0.283103,1.462493,-1.786861,-1.006018,0.986097
1,-0.495139,1.010051,-1.253064,0.981177,-0.992890,0.957886,1.155024,0.687548,-0.120059,-0.664768,-0.645989,0.585778,1.704465,0.467317,1.114266,-0.635317,-0.734267,0.559641,0.994018,-1.014099
2,-1.537686,1.010051,-1.253064,0.981177,-0.532099,0.957886,0.493546,1.381165,0.134244,0.209639,-0.645989,1.392684,1.074968,0.441498,-0.310171,-0.864922,-0.368140,0.559641,0.994018,-1.014099
3,-1.419319,1.010051,1.198517,-1.019184,-0.992890,-1.043966,-1.215274,1.034357,-0.261339,0.646842,-0.151168,1.286750,1.236971,0.594569,0.876859,0.512708,-0.002014,0.559641,-1.006018,-1.014099
4,1.325906,1.010051,-0.395011,-1.019184,2.002254,0.957886,0.658915,0.340740,0.021220,-1.101971,0.673534,1.268718,-0.091452,-0.657666,-1.022389,-0.864922,0.730240,0.559641,0.994018,-1.014099

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
X = df_feat
y = df['price_range']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=100)

In [29]:
from sklearn.svm import SVC

svc = SVC()

In [30]:
from sklearn.model_selection import RandomizedSearchCV

In [31]:
C = [float(x) for x in np.linspace(start = 0.02, stop = 50, num = 150)]

grid = {
    'kernel': ['linear', 'poly','rbf','sigmoid'],
    'C': C,
    'gamma': ['auto']
}

In [32]:
svc_cv = RandomizedSearchCV(estimator = svc, param_distributions = grid, cv = 5, n_iter = 50, verbose = 1)

In [33]:
svc_cv.fit(X_train, y_train)

Fitting 5 folds for each of 50 candidates, totalling 250 fits

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done 250 out of 250 | elapsed:   21.2s finished

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=50,
                   param_distributions={'C': [0.02, 0.3554362416107383,
                                              0.6908724832214765,
                                              1.026308724832215,
                                              1.361744966442953,
                                              1.6971812080536912,
                                              2.03261744966443,
                                              2.368053691275168,
                                              2.703489932885906,
                                              3.0389261744966443,
                                              3.3743624161073824,
                                              3.709798657718121,
                                              4.045234899328859,
                                              4.380671140939597,
                                              4.7161073825503355,
                                              5.051543624161074,
                                              5.386979865771812,
                                              5.72241610738255,
                                              6.057852348993288,
                                              6.393288590604026,
                                              6.728724832214764,
                                              7.064161073825503,
                                              7.3995973154362416,
                                              7.73503355704698,
                                              8.070469798657719,
                                              8.405906040268457,
                                              8.741342281879195,
                                              9.076778523489933,
                                              9.412214765100671,
                                              9.74765100671141, ...],
                                        'gamma': ['auto'],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']},
                   verbose=1)

In [34]:
params = svc_cv.best_params_

In [35]:
svc_final = SVC(**params)
svc_final.fit(X_train, y_train)

SVC(C=30.88013422818792, gamma='auto', kernel='linear')

In [36]:
from sklearn.metrics import confusion_matrix, classification_report

predictions = svc_final.predict(X_test)

In [37]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[100   0   0   0]
 [  3  89   7   0]
 [  0   3  92   1]
 [  0   0   3 102]]
              precision    recall  f1-score   support

         0.0       0.97      1.00      0.99       100
         1.0       0.97      0.90      0.93        99
         2.0       0.90      0.96      0.93        96
         3.0       0.99      0.97      0.98       105

    accuracy                           0.96       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.96      0.96      0.96       400